### ISSUE TITLE
Follow scientific python project suggestion 

### ISSUE THREAD

**Issue by Czaki** [napari/napari-tiff#20]
I think that it will be worth to follow this rules.

https://learn.scientific-python.org/development/guides/repo-review/?repo=napari%2Fnapari-tiff&branch=main

**Comment by jni** [comment]
Cool! Yup, agreed, though it's silly that it can't find the tests directory, which does in fact exist.

**Comment by Czaki** [comment]
They assume either use top level test directory or src layout.

**Comment by GenevieveBuckley** [comment]
We are very happy to receive PRs with any of the suggested improvements. I encourage anybody interested to submit one.

However, I am going to close this issue. I don't consider this a bug, especially since many (or all?) of the napari org repos also do not pass this particular tool's set of checks (and as far as I'm aware, don't have a goal of pursuing that either). Since this isn't actively being worked on, a tracking issue isn't necessary for now.
